{% set name = "cresil" %}
{% set version = "1.2.0" %}
{% set sha256 = "89453d01ab157f6097c855417a154da4ea4f1e03a9287f552062f743a800883c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/visanuwan/cresil/archive/refs/heads/master.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 2
  noarch: python
  script:
    - python -c "import re; f=open('setup.py'); t=f.read(); f.close(); t=re.sub(r\"url\s*=\s*['\\']https://gitlab\.com/visanu/cresil['\\']\", \"url='https://github.com/visanuwan/cresil'\", t); f=open('setup.py','w'); f.write(t); f.close()"
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  entry_points:
    - cresil = cresil:main
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - biopython
    - mappy
    - minimap2
    - python-intervaltree
    - tqdm
    - pandas
    - numpy
    - pysam
    - samtools
    - bedtools
    - pybedtools
    - nanofilt
    - tabix
    - bcftools
    - mosdepth
    - python-graphviz
    - networkx
    - matplotlib-base
    - medaka

test:
  commands:
    - cresil --help
    - cresil --version

about:
  home: https://github.com/visanuwan/cresil/tree/master
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Accurate Identification of Extrachromosomal Circular DNA from Long-read Sequences'
  description: |
    CReSIL is a tool for detecting eccDNA from Nanopore reads.
  dev_url: https://github.com/visanuwan/cresil/tree/master
  doc_url: https://github.com/visanuwan/cresil/tree/master

extra:
  identifiers:
    - doi:10.1093/bib/bbac422
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - SiYangming
