{% set name = "cresil" %}
{% set version = "1.2.1" %}
{% set sha256 = "4ed5d46c7a36a42ab52d20b682944ca5b0d372f0c144c6906c2243b8b6caa31b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/piroonj/cresil_nanocircle/-/archive/master/cresil_nanocircle-master.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  noarch: python
  script:
    - mkdir -p $PREFIX/bin
    - cp CReSIL/CReSIL-identify.py $PREFIX/bin/
    - cp CReSIL/CReSIL-trim.py $PREFIX/bin/
    - cp CReSIL/CReSIL-verify.py $PREFIX/bin/
    - chmod +x $PREFIX/bin/CReSIL-*.py
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  host:
    - python >=3.8
  run:
    - python >=3.8
    - biopython
    - mappy
    - minimap2
    - python-intervaltree
    - tqdm
    - pandas
    - numpy
    - pysam
    - samtools
    - bedtools
    - pybedtools
    - nanofilt
    - tabix
    - bcftools
    - mosdepth
    - python-graphviz
    - networkx
    - matplotlib-base

test:
  commands:
    - CReSIL-trim.py -h
    - CReSIL-identify.py -h
    - CReSIL-verify.py -h

about:
  home: https://github.com/visanuwan/cresil/tree/master
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Accurate Identification of Extrachromosomal Circular DNA from Long-read Sequences'
  description: |
    CReSIL is a tool for detecting eccDNA from Nanopore reads.
  dev_url: https://github.com/visanuwan/cresil/tree/master
  doc_url: https://github.com/visanuwan/cresil/tree/master

extra:
  identifiers:
    - doi:10.1093/bib/bbac422
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - SiYangming
