{% set name = "ecc_finder" %}
{% set version = "1.0.0" %}
{% set sha256 = "d5978390d1381eaf0cbd403c7b49acbc25ba3cb511e4b9e4af438834d73e015a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/njaupan/ecc_finder/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - setup_py_fix.patch
    - ecc_finder_import_fix.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  host:
    - python >=3.8,<3.11
    - pip
    - setuptools
  run:
    - python >=3.8,<3.11
    - pysam
    - numpy
    - pandas
    - matplotlib-base
    - pybedtools
    - minimap2
    - bwa
    - samtools
    - bedtools
    - fastp
    - seqtk
    - cd-hit
    - requests

test:
  commands:
    - ecc_finder.py --version
    - ecc_finder.py --help

about:
  home: https://github.com/njaupan/ecc_finder
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: "ecc_finder: A robust and accurate detection tool to detect eccDNA using Illumina and ONT sequencing"
  description: |
    ecc_finder is a tool for detecting extrachromosomal circular DNA (eccDNA) 
    from sequencing data. It supports both Illumina short reads and ONT long reads.
  dev_url: https://github.com/njaupan/ecc_finder
  doc_url: https://github.com/njaupan/ecc_finder

extra:
  identifiers:
    - doi:10.1186/s13059-024-03227-7
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - SiYangming